name: lexedo/games

autoload:
  psr-4:
    lexedo\games\:
      - ''
      - 'src'
      - 'plugin'
    lexedo\games\sys\: '.system'
    lexedo\games\monopoly\: 'plugin/monopoly/src'
    lexedo\games\chess: 'plugin/chesslike/src'


service:
  routes:
    /: {plugin: main}
    cofb: {plugin: cofb}
    tetris: {plugin: tetris}
    sapper: {plugin: sapper}
    monopoly: {plugin: monopoly}
    chess: {plugin: chesslike}

  plugins:
    - plugin
    - plugin/_dev
  models: model

  components:
    gamesProvider: lexedo\games\GamesProvider

  processes:
    games_server:
      class: lexedo\games\GamesServer
      config:
        single: true
