name: lexedo/games

autoload:
  psr-4:
    lexedo\games\:
      - ''
      - 'src'
    lexedo\games\sys\: '.system'

service:
  routes:
    /: {plugin: main}
    manage: {plugin: manage}

  plugins: plugin
  models: model

  components:
    cli: lexedo\games\cli\Cli
    gamesProvider:
      class: lexedo\games\GamesProvider

  processes:
    games_server:
      class: lexedo\games\GamesServer
      config:
        single: true
